language: node_js
cache: yarn
node_js:
  - '10'
script:
  - yarn lint
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
